import { DigestRun } from "@/lib/digest-types";

export type DigestFeedItem = {
  id: string;
  title: string;
  url: string;
  topic: string;
  summary: string;
  publishedAt?: string;
  feedName?: string;
};

function escapeXml(value: string) {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

export function buildDigestFeedXml(run: DigestRun | null, articles: DigestFeedItem[]) {
  const buildDate = run?.date ?? new Date().toISOString();
  const items = articles
    .map((article) => {
      const description = `${article.summary}${article.feedName ? `\n\nSource: ${article.feedName}` : ""}`;
      return [
        "    <item>",
        `      <title>${escapeXml(article.title)}</title>`,
        `      <link>${escapeXml(article.url)}</link>`,
        `      <guid isPermaLink="false">${escapeXml(article.id)}</guid>`,
        `      <pubDate>${new Date(article.publishedAt ?? buildDate).toUTCString()}</pubDate>`,
        `      <category>${escapeXml(article.topic)}</category>`,
        `      <description>${escapeXml(description)}</description>`,
        "    </item>",
      ].join("\n");
    })
    .join("\n");

  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<rss version="2.0">',
    "  <channel>",
    "    <title>Tech Digest Feed</title>",
    "    <description>Latest curated digest output generated by Digest Manager.</description>",
    "    <link>http://localhost/digest-feed</link>",
    `    <lastBuildDate>${new Date(buildDate).toUTCString()}</lastBuildDate>`,
    items,
    "  </channel>",
    "</rss>",
  ].join("\n");
}
