begin;
insert into public.digest_articles (id, feed_id, feed_name, title, url, topic, published_at, fetched_at, full_text, summary)
values
  ('article-z920xasg', 'feed-techcrunch', 'TechCrunch', 'PopSockets founder David Barnett talks about building a viral business', 'https://techcrunch.com/2026/03/07/popsockets-founder-david-barnett-talks-about-building-a-viral-business/', 'Technology', '2026-03-07T18:40:00.000Z'::timestamptz, '2026-03-08T15:11:45.441Z'::timestamptz, 'David Barnett, founder of PopSocket, stops by Equity to talk about scaling the business and what he''s learned as a leader.', 'David Barnett, founder of PopSocket, stops by Equity to talk about scaling the business and what he''s learned as a leader.'),
  ('article-4w7yjy5k', 'feed-techcrunch', 'TechCrunch', 'OpenAI delays ChatGPT’s ‘adult mode’ again', 'https://techcrunch.com/2026/03/07/openai-delays-chatgpts-adult-mode-again/', 'Technology', '2026-03-07T17:28:41.000Z'::timestamptz, '2026-03-08T15:11:45.441Z'::timestamptz, 'The feature, which will give verified adult users access to erotica and other adult content, had already been delayed from December.', 'The feature, which will give verified adult users access to erotica and other adult content, had already been delayed from December.'),
  ('article-22wx6xn5', 'feed-ars', 'Ars Technica', 'A unicorn-like Spinosaurus found in the Sahara', 'https://arstechnica.com/science/2026/03/a-unicorn-like-spinosaurus-found-in-the-sahara/', 'Technology', '2026-03-07T12:30:56.000Z'::timestamptz, '2026-03-08T15:11:45.441Z'::timestamptz, 'The Spinosaurus is a sail-backed, crocodile-snouted dinosaur that Hollywood depicted as a giant terrestrial predator capable of taking down a T. rex in Jurassic Park 3 . Then they changed their mind and made it a fully aquatic diver in Jurassic World Rebirth —a rendering that was more in line with the latest paleontological knowledge. But now, deep in the Sahara Desert, a team of researchers led by Paul C. Sereno, a paleontologist at the University of Chicago, discovered new Spinosaurus fossils suggesting both scientists and filmmakers might have got it all wrong again. The Spinosaurus most likely wasn’t an aquatic diver because, apparently, it couldn’t dive. Bones in the sand While the T. rex -beating version of the Spinosaurus was considered unlikely due to its relatively fragile skull, the newer depiction as an aquatic diver made more sense in light of paleontological evidence. Until now, all remains of these predators were pulled from coastal deposits near ancient seas and oceans. That geographic distribution was consistent with the aquatic lifestyle interpretation . If a creature lived on the coast, maybe it swam out to sea like a prehistoric seal, only crawling out to the beaches to rest just as it was depicted in Jurassic World Rebirth . Read full article Comments', 'The Spinosaurus is a sail-backed, crocodile-snouted dinosaur that Hollywood depicted as a giant terrestrial predator capable of taking down a T. rex in Jurassic Park 3.'),
  ('article-b0xsdbhf', 'feed-ars', 'Ars Technica', 'From Iran to Ukraine, everyone''s trying to hack security cameras', 'https://arstechnica.com/security/2026/03/from-iran-to-ukraine-everyones-trying-to-hack-security-cameras/', 'Technology', '2026-03-07T11:30:06.000Z'::timestamptz, '2026-03-08T15:11:45.441Z'::timestamptz, 'For decades, satellites, drones , and human spotters have all been part of war’s surveillance and reconnaissance tool kit. In an age of cheap, insecure, Internet-connected consumer devices, however, militaries have gained another powerful set of eyes on the ground: every hackable security camera installed outside a home or on a city street, pointed at potential bombing targets. On Wednesday, Tel Aviv–based security firm Check Point released new research describing hundreds of hacking attempts that targeted consumer-grade security cameras around the Middle East —with many apparently timed to Iran''s recent missile and drone strikes on targets that included Israel, Qatar, and Cyprus. Those camera-hijacking efforts, some of which Check Point has attributed to a hacker group that''s been previously linked to Iranian intelligence, suggest that Iran''s military has tried to use civilian surveillance cameras as a means to spot targets, plan strikes, or assess damage from its attacks as it retaliates for the US and Israeli bombings that have sparked a widening war in the region. Iran wouldn''t be the first to adopt that camera-hacking surveillance tactic. Earlier this week, the Financial Times reported that the Israeli military had accessed “nearly all” the traffic cameras in Iran''s capital of Tehran and, in partnership with the CIA, used them to target the air strike that killed Ayatollah Ali Khamenei, Iran’s supreme leader. In Ukraine, the country''s officials have warned for years that Russia has hacked consumer surveillance cameras to target strikes and spy on troop movements—while Ukrainian hackers have hijacked Russian cameras to surveil Russian troops and perhaps even to monitor its own attacks . Read full article Comments', 'For decades, satellites, drones, and human spotters have all been part of war’s surveillance and reconnaissance tool kit. In an age of cheap, insecure, Internet-connected consumer devices, however, militaries have gained another powerful set of eyes on the ground: every hackable security camera installed outside a home or on a city street, pointed at potential bombing targets.'),
  ('article-k35xjdjn', 'feed-techcrunch', 'TechCrunch', 'Robinhood’s startup fund stumbles in NYSE debut', 'https://techcrunch.com/2026/03/06/robinhoods-startup-fund-stumbles-in-nyse-debut/', 'Technology', '2026-03-07T02:04:43.000Z'::timestamptz, '2026-03-08T15:11:45.441Z'::timestamptz, 'The fund currently offers retail investors exposure to eight startups, including Mercor, Ramp, and Stripe, with plans to expand its portfolio.', 'The fund currently offers retail investors exposure to eight startups, including Mercor, Ramp, and Stripe, with plans to expand its portfolio.'),
  ('article-ojzc2dqg', 'feed-hn', 'Hacker News', 'Some Words on WigglyPaint', 'https://beyondloom.com/blog/onwigglypaint.html', 'Technology', '2026-03-07T01:21:47.000Z'::timestamptz, '2026-03-08T15:11:45.441Z'::timestamptz, 'Comments', 'Comments'),
  ('article-8lkw2c2d', 'feed-ars', 'Ars Technica', 'Ding-dong! The Exploration Upper Stage is dead', 'https://arstechnica.com/space/2026/03/ding-dong-the-exploration-upper-stage-is-dead/', 'Technology', '2026-03-06T23:40:35.000Z'::timestamptz, '2026-03-08T15:11:45.441Z'::timestamptz, 'In his 1961 novel The Winter of Our Discontent, John Steinbeck wrote of loss, "It''s so much darker when a light goes out than it would have been if it had never shone." The death of NASA''s Exploration Upper Stage today represents the inverse of that sentiment. The world of spaceflight is so much brighter now that its light has gone out. The rocket''s death came via a seemingly pedestrian notice posted on a government procurement website: "NASA/MSFC intends to issue a sole source contract to acquire next-generation upper stages for use in Space Launch System (SLS) Artemis IV and Artemis V from United Launch Alliance (ULA)." Read full article Comments', 'In his 1961 novel The Winter of Our Discontent, John Steinbeck wrote of loss, "It''s so much darker when a light goes out than it would have been if it had never shone." The death of NASA''s Exploration Upper Stage today represents the inverse of that sentiment. The world of spaceflight is so much brighter now that its light has gone out.'),
  ('article-yjh14ibq', 'feed-ars', 'Ars Technica', 'Satellite firm pauses imagery after revealing Iran''s attacks on US bases', 'https://arstechnica.com/space/2026/03/satellite-firm-pauses-imagery-after-revealing-irans-attacks-on-us-bases/', 'Technology', '2026-03-06T22:49:48.000Z'::timestamptz, '2026-03-08T15:11:45.441Z'::timestamptz, 'Planet Labs, one of the world''s leading commercial satellite imaging companies, said Friday it is placing a hold on releasing imagery of some parts of the Middle East as a regional war enters its second week. The company, which brands itself as Planet, operates a fleet of several hundred Earth-imaging satellites designed to record views of every landmass on Earth at least once per day. Its customers include think tanks, NGOs, academic institutions, news media, and commercial users in the agriculture, forestry, and energy industries, among others. Planet also holds lucrative contracts selling overhead imagery to the US military and US government intelligence agencies. Read full article Comments', 'Planet Labs, one of the world''s leading commercial satellite imaging companies, said Friday it is placing a hold on releasing imagery of some parts of the Middle East as a regional war enters its second week. The company, which brands itself as Planet, operates a fleet of several hundred Earth-imaging satellites designed to record views of every landmass on Earth at least once per day.'),
  ('article-r38v8aad', 'feed-techcrunch', 'TechCrunch', 'X is testing a new ad format that connects posts with products', 'https://techcrunch.com/2026/03/06/x-is-testing-a-new-ad-format-that-connects-posts-with-products/', 'Technology', '2026-03-06T22:41:26.000Z'::timestamptz, '2026-03-08T15:11:45.441Z'::timestamptz, 'An ad test on X promotes Musk''s Starlink beneath original content.', 'An ad test on X promotes Musk''s Starlink beneath original content.'),
  ('article-vh3werxx', 'feed-techcrunch', 'TechCrunch', 'Nintendo sues the US government for a refund on tariffs', 'https://techcrunch.com/2026/03/06/nintendo-sues-the-u-s-government-for-a-refund-on-tariffs/', 'Technology', '2026-03-06T22:35:35.000Z'::timestamptz, '2026-03-08T15:11:45.441Z'::timestamptz, 'This lawsuit comes after a Supreme Court decision struck down some of the president''s sweeping tariffs, which had impacted Nintendo and thousands of other companies.', 'This lawsuit comes after a Supreme Court decision struck down some of the president''s sweeping tariffs, which had impacted Nintendo and thousands of other companies.')
on conflict (url) do update set
  feed_id = excluded.feed_id,
  feed_name = excluded.feed_name,
  title = excluded.title,
  topic = excluded.topic,
  published_at = excluded.published_at,
  fetched_at = excluded.fetched_at,
  full_text = excluded.full_text,
  summary = excluded.summary;
commit;
