begin;
insert into public.digest_articles (id, feed_id, feed_name, title, url, topic, published_at, fetched_at, full_text, summary)
values
  ('article-274l68eo', 'feed-darkreading', 'Dark Reading', 'China''s Silver Dragon Razes Governments in EU, SE Asia', 'https://www.darkreading.com/threat-intelligence/china-silver-dragon-governments-eu-se-asia', 'Cybersecurity', '2026-03-04T11:26:55.000Z'::timestamptz, '2026-03-08T15:11:45.441Z'::timestamptz, 'The emerging actor, part of the APT41 nexus, gains initial access via phishing, and uses legitimate network services to obscure cyber espionage activities.', 'The emerging actor, part of the APT41 nexus, gains initial access via phishing, and uses legitimate network services to obscure cyber espionage activities.'),
  ('article-1afx5skr', 'feed-openai', 'OpenAI News', 'Extending single-minus amplitudes to gravitons', 'https://openai.com/index/extending-single-minus-amplitudes-to-gravitons', 'AI', '2026-03-04T10:00:00.000Z'::timestamptz, '2026-03-08T15:11:45.441Z'::timestamptz, 'A new preprint extends single-minus amplitudes to gravitons, with GPT-5.2 Pro helping derive and verify nonzero graviton tree amplitudes in quantum gravity.', 'A new preprint extends single-minus amplitudes to gravitons, with GPT-5.2 Pro helping derive and verify nonzero graviton tree amplitudes in quantum gravity.'),
  ('article-jft5vl47', 'feed-hn', 'Hacker News', 'From RGB to L*a*b* color space (2024)', 'https://kaizoudou.com/from-rgb-to-lab-color-space/', 'Technology', '2026-03-04T09:24:13.000Z'::timestamptz, '2026-03-08T15:11:45.441Z'::timestamptz, 'Comments', 'Comments'),
  ('article-9g213tge', 'feed-openai', 'OpenAI News', 'Understanding AI and learning outcomes', 'https://openai.com/index/understanding-ai-and-learning-outcomes', 'AI', '2026-03-04T00:00:00.000Z'::timestamptz, '2026-03-08T15:11:45.441Z'::timestamptz, 'OpenAI introduces the Learning Outcomes Measurement Suite to assess AI’s impact on student learning across diverse educational environments over time.', 'OpenAI introduces the Learning Outcomes Measurement Suite to assess AI’s impact on student learning across diverse educational environments over time.'),
  ('article-5jbl1fig', 'feed-openai', 'OpenAI News', 'How Axios uses AI to help deliver high-impact local journalism', 'https://openai.com/index/axios-allison-murphy', 'AI', '2026-03-04T00:00:00.000Z'::timestamptz, '2026-03-08T15:11:45.441Z'::timestamptz, 'Axios COO Allison Murphy explains how the company uses AI to support local reporters, streamline newsroom workflows, and deliver high-impact local journalism at scale.', 'Axios COO Allison Murphy explains how the company uses AI to support local reporters, streamline newsroom workflows, and deliver high-impact local journalism at scale.'),
  ('article-i32jxbb2', 'feed-hn', 'Hacker News', 'The Lobster Programming Language', 'https://strlen.com/lobster/', 'Technology', '2026-03-03T22:24:54.000Z'::timestamptz, '2026-03-08T15:11:45.441Z'::timestamptz, 'Comments', 'Comments'),
  ('article-jaxl5gli', 'feed-darkreading', 'Dark Reading', 'Indian APT ''Sloppy Lemming'' Targets Defense, Critical Infrastructure', 'https://www.darkreading.com/threat-intelligence/india-apt-sloppy-lemming-defense-critical-infrastructure', 'Cybersecurity', '2026-03-03T22:24:22.000Z'::timestamptz, '2026-03-08T15:11:45.441Z'::timestamptz, 'India-nexus cyber threat actors are growing more active and sophisticated, using custom tools coded in Rust and cloud-based command and control.', 'India-nexus cyber threat actors are growing more active and sophisticated, using custom tools coded in Rust and cloud-based command and control.'),
  ('article-rmq1v8qm', 'feed-darkreading', 'Dark Reading', 'Vehicle Tire Pressure Sensors Enable Silent Tracking', 'https://www.darkreading.com/ics-ot-security/tire-pressure-sensors-silent-tracking', 'Cybersecurity', '2026-03-03T20:53:39.000Z'::timestamptz, '2026-03-08T15:11:45.441Z'::timestamptz, 'Like many other features and systems in modern cars, tire pressure sensors leak sensitive data that can be abused by threat actors.', 'Like many other features and systems in modern cars, tire pressure sensors leak sensitive data that can be abused by threat actors.'),
  ('article-8tgbiqzm', 'feed-darkreading', 'Dark Reading', 'Qualcomm Zero-Day Exploited in Targeted Android Attacks', 'https://www.darkreading.com/threat-intelligence/qualcomm-zero-day-exploited-targeted-android-attacks', 'Cybersecurity', '2026-03-03T20:28:05.000Z'::timestamptz, '2026-03-08T15:11:45.441Z'::timestamptz, 'The exploitation activity against CVE-2026-21385, a high-severity memory corruption flaw, could be tied to commercial spyware or nation-state threat groups.', 'The exploitation activity against CVE-2026-21385, a high-severity memory corruption flaw, could be tied to commercial spyware or nation-state threat groups.'),
  ('article-h22yxa9c', 'feed-darkreading', 'Dark Reading', 'Speakeasies to Shadow AI: Banning AI Browsers Will Fail', 'https://www.darkreading.com/cyber-risk/speakeasies-shadow-ai-banning-ai-browsers-fail', 'Cybersecurity', '2026-03-03T17:40:21.000Z'::timestamptz, '2026-03-08T15:11:45.441Z'::timestamptz, 'Lessons from history highlight why AI-enabled browsers require controlled enablement.', 'Lessons from history highlight why AI-enabled browsers require controlled enablement.')
on conflict (url) do update set
  feed_id = excluded.feed_id,
  feed_name = excluded.feed_name,
  title = excluded.title,
  topic = excluded.topic,
  published_at = excluded.published_at,
  fetched_at = excluded.fetched_at,
  full_text = excluded.full_text,
  summary = excluded.summary;
commit;
