begin;
insert into public.digest_articles (id, feed_id, feed_name, title, url, topic, published_at, fetched_at, full_text, summary)
values
  ('article-cspc8tzc', 'feed-nvd', 'NIST CVE Feed', 'CVE-2025-15597 (MEDIUM)', 'https://github.com/dataease/SQLBot/', 'Cybersecurity', '2026-03-02T05:16:22.330Z'::timestamptz, '2026-03-08T15:11:45.441Z'::timestamptz, 'A vulnerability has been found in Dataease SQLBot up to 1.4.0. This affects an unknown function of the file backend/apps/system/api/assistant.py of the component API Endpoint. Such manipulation leads to improper access controls. It is possible to launch the attack remotely. The exploit has been disclosed to the public and may be used. Upgrading to version 1.5.0 mitigates this issue. The name of the patch is d640ac31d1ce64ce90e06cf7081163915c9fc28c. Upgrading the affected component is recommended. Multiple endpoints are affected. The vendor was contacted early about this disclosure.', 'A vulnerability has been found in Dataease SQLBot up to 1.4.0. This affects an unknown function of the file backend/apps/system/api/assistant.py of the component API Endpoint.'),
  ('article-a5ylpnkl', 'feed-nvd', 'NIST CVE Feed', 'CVE-2026-3412 (MEDIUM)', 'https://github.com/dyh1213-wq/cve/issues/1', 'Cybersecurity', '2026-03-02T04:15:59.723Z'::timestamptz, '2026-03-08T15:11:45.441Z'::timestamptz, 'A vulnerability was detected in itsourcecode University Management System 1.0. This affects an unknown part of the file /att_single_view.php. The manipulation of the argument dt results in cross site scripting. The attack can be executed remotely. The exploit is now public and may be used.', 'A vulnerability was detected in itsourcecode University Management System 1.0. This affects an unknown part of the file /att_single_view.php.'),
  ('article-mnnfssd7', 'feed-nvd', 'NIST CVE Feed', 'CVE-2026-3411 (HIGH)', 'https://github.com/dyh1213-wq/cve/issues/2', 'Cybersecurity', '2026-03-02T03:16:19.957Z'::timestamptz, '2026-03-08T15:11:45.441Z'::timestamptz, 'A security vulnerability has been detected in itsourcecode University Management System 1.0. Affected by this issue is some unknown functionality of the file /admin_single_student_update.php. The manipulation of the argument ID leads to sql injection. Remote exploitation of the attack is possible. The exploit has been disclosed publicly and may be used.', 'A security vulnerability has been detected in itsourcecode University Management System 1.0. Affected by this issue is some unknown functionality of the file /admin_single_student_update.php.'),
  ('article-cys41qzf', 'feed-nvd', 'NIST CVE Feed', 'CVE-2026-3410 (HIGH)', 'https://github.com/DeelBran-7/hyf/issues/1', 'Cybersecurity', '2026-03-02T03:16:19.717Z'::timestamptz, '2026-03-08T15:11:45.441Z'::timestamptz, 'A weakness has been identified in itsourcecode Society Management System 1.0. Affected by this vulnerability is an unknown functionality of the file /admin/check_studid.php. Executing a manipulation of the argument student_id can lead to sql injection. The attack may be launched remotely. The exploit has been made available to the public and could be used for attacks.', 'A weakness has been identified in itsourcecode Society Management System 1.0. Affected by this vulnerability is an unknown functionality of the file /admin/check_studid.php.'),
  ('article-68u2m0r4', 'feed-nvd', 'NIST CVE Feed', 'CVE-2026-3409 (HIGH)', 'https://gist.github.com/YLChen-007/d2799d8b2077e50658f12a45bcae9b70', 'Cybersecurity', '2026-03-02T03:16:17.450Z'::timestamptz, '2026-03-08T15:11:45.441Z'::timestamptz, 'A security flaw has been discovered in eosphoros-ai db-gpt 0.7.5. Affected is the function importlib.machinery.SourceFileLoader.exec_module of the file /api/v1/serve/awel/flow/import of the component Flow Import Endpoint. Performing a manipulation as part of File results in code injection. The attack may be initiated remotely. The exploit has been released to the public and may be used for attacks. The vendor was contacted early about this disclosure but did not respond in any way.', 'A security flaw has been discovered in eosphoros-ai db-gpt 0.7.5. Affected is the function importlib.machinery.SourceFileLoader.exec_module of the file /api/v1/serve/awel/flow/import of the component Flow Import Endpoint.'),
  ('article-p43khzgj', 'feed-nvd', 'NIST CVE Feed', 'CVE-2026-3408 (MEDIUM)', 'https://github.com/VedantMadane/openbabel/commit/e23a224b8fd9d7c2a7cde9ef4ec6afb4c05aa08a', 'Cybersecurity', '2026-03-02T02:16:06.023Z'::timestamptz, '2026-03-08T15:11:45.441Z'::timestamptz, 'A vulnerability was identified in Open Babel up to 3.1.1. This impacts the function OBAtom::GetExplicitValence of the file isrc/atom.cpp of the component CDXML File Handler. Such manipulation leads to null pointer dereference. The attack can be launched remotely. The exploit is publicly available and might be used. The name of the patch is e23a224b8fd9d7c2a7cde9ef4ec6afb4c05aa08a. It is best practice to apply a patch to resolve this issue.', 'A vulnerability was identified in Open Babel up to 3.1.1. This impacts the function OBAtom::GetExplicitValence of the file isrc/atom.cpp of the component CDXML File Handler.'),
  ('article-v249mxxx', 'feed-nvd', 'NIST CVE Feed', 'CVE-2026-3407 (LOW)', 'https://github.com/YosysHQ/yosys/', 'Cybersecurity', '2026-03-02T01:16:01.600Z'::timestamptz, '2026-03-08T15:11:45.441Z'::timestamptz, 'A vulnerability was determined in YosysHQ yosys up to 0.62. This affects the function Yosys::RTLIL::Const::set of the file kernel/rtlil.h of the component BLIF File Parser. This manipulation causes heap-based buffer overflow. It is possible to launch the attack on the local host. The exploit has been publicly disclosed and may be utilized. Applying a patch is the recommended action to fix this issue. It appears that the issue is not reproducible all the time.', 'A vulnerability was determined in YosysHQ yosys up to 0.62. This affects the function Yosys::RTLIL::Const::set of the file kernel/rtlil.h of the component BLIF File Parser.'),
  ('article-twma9qps', 'feed-nvd', 'NIST CVE Feed', 'CVE-2026-3406 (HIGH)', 'https://github.com/ubfbuz3/cve/issues/55', 'Cybersecurity', '2026-03-02T01:16:01.357Z'::timestamptz, '2026-03-08T15:11:45.441Z'::timestamptz, 'A vulnerability was found in projectworlds Online Art Gallery Shop 1.0. The impacted element is an unknown function of the file /admin/registration.php of the component Registration Handler. The manipulation of the argument fname results in sql injection. It is possible to launch the attack remotely. The exploit has been made public and could be used.', 'A vulnerability was found in projectworlds Online Art Gallery Shop 1.0. The impacted element is an unknown function of the file /admin/registration.php of the component Registration Handler.'),
  ('article-l0374amf', 'feed-nvd', 'NIST CVE Feed', 'CVE-2026-3405 (LOW)', 'https://vuldb.com/?ctiid.348300', 'Cybersecurity', '2026-03-02T00:16:20.013Z'::timestamptz, '2026-03-08T15:11:45.441Z'::timestamptz, 'A vulnerability has been found in thinkgem JeeSite up to 5.15.1. The affected element is an unknown function of the component Connection Handler. The manipulation leads to path traversal. It is possible to initiate the attack remotely. The attack is considered to have high complexity. The exploitability is described as difficult. The exploit has been disclosed to the public and may be used. The vendor was contacted early about this disclosure but did not respond in any way.', 'A vulnerability has been found in thinkgem JeeSite up to 5.15.1. The affected element is an unknown function of the component Connection Handler.'),
  ('article-jegrx9af', 'feed-nvd', 'NIST CVE Feed', 'CVE-2026-3404 (MEDIUM)', 'https://vuldb.com/?ctiid.348299', 'Cybersecurity', '2026-03-02T00:16:19.800Z'::timestamptz, '2026-03-08T15:11:45.441Z'::timestamptz, 'A flaw has been found in thinkgem JeeSite up to 5.15.1. Impacted is an unknown function of the file /com/jeesite/common/shiro/cas/CasOutHandler.java of the component Endpoint. Executing a manipulation can lead to xml external entity reference. The attack may be performed from remote. Attacks of this nature are highly complex. The exploitability is considered difficult. The exploit has been published and may be used. The vendor was contacted early about this disclosure but did not respond in any way.', 'A flaw has been found in thinkgem JeeSite up to 5.15.1. Impacted is an unknown function of the file /com/jeesite/common/shiro/cas/CasOutHandler.java of the component Endpoint.')
on conflict (url) do update set
  feed_id = excluded.feed_id,
  feed_name = excluded.feed_name,
  title = excluded.title,
  topic = excluded.topic,
  published_at = excluded.published_at,
  fetched_at = excluded.fetched_at,
  full_text = excluded.full_text,
  summary = excluded.summary;
commit;
