begin;
insert into public.digest_articles (id, feed_id, feed_name, title, url, topic, published_at, fetched_at, full_text, summary)
values
  ('article-xjtgpvxk', 'feed-hn', 'Hacker News', 'Sem – Semantic version control. Entity-level diffs on top of Git', 'https://github.com/ataraxy-labs/sem', 'Technology', '2026-03-08T06:01:26.000Z'::timestamptz, '2026-03-08T15:11:45.441Z'::timestamptz, 'Comments', 'Comments'),
  ('article-lvfcpqed', 'feed-techcrunch', 'TechCrunch', 'Push for $40 smartphones builds momentum, but still faces cost hurdles', 'https://techcrunch.com/2026/03/07/push-for-40-smartphones-builds-momentum-but-still-faces-cost-hurdles/', 'Technology', '2026-03-08T05:00:00.000Z'::timestamptz, '2026-03-08T15:11:45.441Z'::timestamptz, 'A coalition of telecom operators and device makers is pushing $40 smartphones to bring up to 20 million people online, but rising component costs threaten the plan.', 'A coalition of telecom operators and device makers is pushing $40 smartphones to bring up to 20 million people online, but rising component costs threaten the plan.'),
  ('article-9j4qa6x8', 'feed-hn', 'Hacker News', 'Warn about PyPy being unmaintained', 'https://github.com/astral-sh/uv/pull/17643', 'Technology', '2026-03-08T01:35:21.000Z'::timestamptz, '2026-03-08T15:11:45.441Z'::timestamptz, 'Comments', 'Comments'),
  ('article-n17yry1p', 'feed-hn', 'Hacker News', 'Cloud VM benchmarks 2026', 'https://devblog.ecuadors.net/cloud-vm-benchmarks-2026-performance-price-1i1m.html', 'Technology', '2026-03-08T00:44:32.000Z'::timestamptz, '2026-03-08T15:11:45.441Z'::timestamptz, 'Comments', 'Comments'),
  ('article-00i4et7l', 'feed-techcrunch', 'TechCrunch', 'Google just gave Sundar Pichai a $692M pay package', 'https://techcrunch.com/2026/03/07/google-just-gave-sundar-pichai-a-692m-pay-package/', 'Technology', '2026-03-08T00:20:10.000Z'::timestamptz, '2026-03-08T15:11:45.441Z'::timestamptz, 'Most of it is tied to performance, including new stock incentives linked to Waymo and Wing, its drone delivery venture.', 'Most of it is tied to performance, including new stock incentives linked to Waymo and Wing, its drone delivery venture.'),
  ('article-btjffmij', 'feed-hn', 'Hacker News', 'How to run Qwen 3.5 locally', 'https://unsloth.ai/docs/models/qwen3.5', 'Technology', '2026-03-07T23:32:17.000Z'::timestamptz, '2026-03-08T15:11:45.441Z'::timestamptz, 'Comments', 'Comments'),
  ('article-he0d8cs0', 'feed-techcrunch', 'TechCrunch', 'Grammarly’s ‘expert review’ is just missing the actual experts', 'https://techcrunch.com/2026/03/07/grammarlys-expert-review-is-just-missing-the-actual-experts/', 'Technology', '2026-03-07T22:56:31.000Z'::timestamptz, '2026-03-08T15:11:45.441Z'::timestamptz, 'A recently-added feature in Grammarly purports to improve users’ writing with help from the world''s great writers and thinkers — and some tech journalists, too.', 'A recently-added feature in Grammarly purports to improve users’ writing with help from the world''s great writers and thinkers — and some tech journalists, too.'),
  ('article-kupc03ah', 'feed-ars', 'Ars Technica', 'Hunting for elusive "ghost elephants"', 'https://arstechnica.com/science/2026/03/hunting-for-elusive-ghost-elephants/', 'Technology', '2026-03-07T21:06:46.000Z'::timestamptz, '2026-03-08T15:11:45.441Z'::timestamptz, 'Deep in the Angolan Highlands lurks a rumored new species of elephant. Conservationist and ornithologist Steve Boyes has been searching for this elusive herd for years and the story of his journey is the focus of Ghost Elephants , a haunting, evocative documentary directed by Werner Herzog . The film debuted at the Venice International Film Festival last summer and is now coming to National Geographic and Disney+. It might seem unusual for an ornithologist to embark on a quest to find remote pachyderms, but for Boyes the connection is perfectly natural. He grew up in South Africa and wanted nothing more than to be an explorer, just like the people he read about every month in National Geographic magazine. "I grew up waiting for the magazine to arrive; I wanted the maps," Boyes told Ars. "Those would become my garden, or the field beyond, or the river—wild places imagined and real." Boyes'' parents frequently took him and his brother out into the wild, including visits to Botswana and Tanzania. "We used to embed ourselves in baboon troops and walk with impalas," said Boyes, and while his brother feared elephants, Boyes was walking with them from a young age. Ghost Elephants contains some gorgeous underwater footage of elephant feet plodding through the water, and elephants swimming on their sides, behavior that matches Boyes'' own experiences with the animals. Under the right circumstances, if they don''t feel threatened, elephants "will come and swim around you and with you and interact with you," he said. "So elephants have always fascinated me." Read full article Comments', 'Deep in the Angolan Highlands lurks a rumored new species of elephant. Conservationist and ornithologist Steve Boyes has been searching for this elusive herd for years and the story of his journey is the focus of Ghost Elephants, a haunting, evocative documentary directed by Werner Herzog.'),
  ('article-1u3npr5y', 'feed-techcrunch', 'TechCrunch', 'OpenAI hardware exec Caitlin Kalinowski quits in response to Pentagon deal', 'https://techcrunch.com/2026/03/07/openai-robotics-lead-caitlin-kalinowski-quits-in-response-to-pentagon-deal/', 'Technology', '2026-03-07T20:44:25.000Z'::timestamptz, '2026-03-08T15:11:45.441Z'::timestamptz, 'Hardware executive Caitlin Kalinowski announced today that in response to OpenAI''s controversial agreement with the Department of Defense, she’s resigned from her role leading the company''s robotics team.', 'Hardware executive Caitlin Kalinowski announced today that in response to OpenAI''s controversial agreement with the Department of Defense, she’s resigned from her role leading the company''s robotics team.'),
  ('article-r42srhaz', 'feed-hn', 'Hacker News', 'CasNum', 'https://github.com/0x0mer/CasNum', 'Technology', '2026-03-07T20:43:51.000Z'::timestamptz, '2026-03-08T15:11:45.441Z'::timestamptz, 'Comments', 'Comments')
on conflict (url) do update set
  feed_id = excluded.feed_id,
  feed_name = excluded.feed_name,
  title = excluded.title,
  topic = excluded.topic,
  published_at = excluded.published_at,
  fetched_at = excluded.fetched_at,
  full_text = excluded.full_text,
  summary = excluded.summary;
commit;
