begin;
insert into public.digest_articles (id, feed_id, feed_name, title, url, topic, published_at, fetched_at, full_text, summary)
values
  ('article-fyletohw', 'feed-hn', 'Hacker News', 'LibreOffice: Request to the European Commission to adhere to its own guidances', 'https://blog.documentfoundation.org/blog/2026/03/05/cra-guidances/', 'Technology', '2026-03-08T14:09:09.000Z'::timestamptz, '2026-03-08T15:11:45.441Z'::timestamptz, 'Comments', 'Comments'),
  ('article-49of3utj', 'feed-hn', 'Hacker News', 'CLI RSS/Atom feed reader inspired by Taskwarrior, synced using Git', 'https://github.com/kantord/blogtato', 'Technology', '2026-03-08T13:16:14.000Z'::timestamptz, '2026-03-08T15:11:45.441Z'::timestamptz, 'Comments', 'Comments'),
  ('article-433immiy', 'feed-ars', 'Ars Technica', 'Jessica Jones joins the fray in Daredevil: Born Again trailer', 'https://arstechnica.com/culture/2026/03/jessica-jones-joins-the-fray-in-daredevil-born-again-trailer/', 'Technology', '2026-03-08T13:13:03.000Z'::timestamptz, '2026-03-08T15:11:45.441Z'::timestamptz, 'One of our favorite TV shows last year was Daredevil: Born Again , Marvel’s revival of the hugely popular series in the Netflix Defenders universe. Who could resist the magical combination of Charlie Cox as Matt Murdock/Daredevil and Vincent D’Onofrio as his nemesis, crime lord Wilson Fisk/Kingpin? The series quickly earned critical raves and a second season . And Marvel has released a short trailer in advance of the S2 premiere later this month. (Some spoilers below for the first season.) Sure, the fans were shocked when the pilot episode killed off Matt’s best friend and law partner, Foggy Nelson (Elden Hensen), in the first 10 minutes, with his grief-stricken law partner, Karen Page (Deborah Ann Woll), taking her leave from the firm by the pilot’s end. But that creative choice cleared the decks to place the focus squarely on Matt’s and Fisk’s parallel arcs. Matt decided to focus on his legal work while Fisk was elected mayor of New York City, intent on leaving his criminal life behind. But each struggled to remain in the light as the dark sides of their respective natures fought to be released. The result was an entertaining, character-driven series that feels very much a part of its predecessor while still having its own distinctive feel. Read full article Comments', 'One of our favorite TV shows last year was Daredevil: Born Again, Marvel’s revival of the hugely popular series in the Netflix Defenders universe. Who could resist the magical combination of Charlie Cox as Matt Murdock/Daredevil and Vincent D’Onofrio as his nemesis, crime lord Wilson Fisk/Kingpin?'),
  ('article-jjv0rq7f', 'feed-hn', 'Hacker News', 'I ported Linux to the PS5 and turned it into a Steam Machine', 'https://xcancel.com/theflow0/status/2030011206040256841', 'Technology', '2026-03-08T12:40:14.000Z'::timestamptz, '2026-03-08T15:11:45.441Z'::timestamptz, 'Comments', 'Comments'),
  ('article-wx8icaez', 'feed-ars', 'Ars Technica', 'Tiny, long-armed dinosaur leads to rethink of dinosaur miniaturization', 'https://arstechnica.com/science/2026/03/tiny-long-armed-dinosaur-leads-to-rethink-of-dinosaur-miniaturization/', 'Technology', '2026-03-08T11:30:06.000Z'::timestamptz, '2026-03-08T15:11:45.441Z'::timestamptz, 'Alvarezsaurids were mostly small-bodied theropods that paleontologists originally misinterpreted as early flightless birds, only to later recognize them as an ant-eating lineage of non-avian dinosaurs. For years, we suspected that Alvarezsaurids underwent a rare process of evolutionary miniaturization directly coupled to a diet of social insects like ants and termites. It was a tidy hypothesis: They got smaller to become more efficient at catching ants. Now, a recently discovered fossil of one of the smallest alvarezsaurids ever found suggests that the evolution of miniature dinosaurs likely wasn’t as neat and linear as we thought. This new species, called Alnashetri cerropoliciensis , probably did not feed on ants at all. “It was a pursuit predator actively hunting insects and small mammals,” said Peter Makovicky, a paleontologist at the University of Minnesota. The oddball Alverezsaurids, found mostly in the Late Cretaceous rocks of Asia and South America, had short forelimbs tipped with a single oversized thumb claw built for digging. They also had minute teeth and sensory adaptations akin to those in modern nocturnal birds—everything necessary to work on termite mounds. “The explanation of their small body size has been tied to this specialization,” Makovicky explained. Read full article Comments', 'Alvarezsaurids were mostly small-bodied theropods that paleontologists originally misinterpreted as early flightless birds, only to later recognize them as an ant-eating lineage of non-avian dinosaurs. For years, we suspected that Alvarezsaurids underwent a rare process of evolutionary miniaturization directly coupled to a diet of social insects like ants and termites.'),
  ('article-z7bcw0ey', 'feed-hn', 'Hacker News', 'Show HN: Eyot, A programming language where the GPU is just another thread', 'https://cowleyforniastudios.com/2026/03/08/announcing-eyot/', 'Technology', '2026-03-08T11:04:04.000Z'::timestamptz, '2026-03-08T15:11:45.441Z'::timestamptz, 'Comments', 'Comments'),
  ('article-cs2qlasf', 'feed-hn', 'Hacker News', 'Notes on Writing WASM', 'https://notes.brooklynzelenka.com/Blog/Notes-on-Writing-Wasm', 'Technology', '2026-03-08T09:24:54.000Z'::timestamptz, '2026-03-08T15:11:45.441Z'::timestamptz, 'Comments', 'Comments'),
  ('article-g51hex4v', 'feed-hn', 'Hacker News', 'SWE-CI: Evaluating Agent Capabilities in Maintaining Codebases via CI', 'https://arxiv.org/abs/2603.03823', 'Technology', '2026-03-08T08:11:50.000Z'::timestamptz, '2026-03-08T15:11:45.441Z'::timestamptz, 'Comments', 'Comments'),
  ('article-9cj5cfry', 'feed-hn', 'Hacker News', 'Show HN: Curiosity – DIY 6" Newtonian Reflector Telescope', 'https://curiosity-telescope.vercel.app/', 'Technology', '2026-03-08T07:16:15.000Z'::timestamptz, '2026-03-08T15:11:45.441Z'::timestamptz, 'Comments', 'Comments'),
  ('article-zcbwxdrc', 'feed-techcrunch', 'TechCrunch', 'A roadmap for AI, if anyone will listen', 'https://techcrunch.com/2026/03/07/a-roadmap-for-ai-if-anyone-will-listen/', 'Technology', '2026-03-08T06:05:26.000Z'::timestamptz, '2026-03-08T15:11:45.441Z'::timestamptz, 'The Pro-Human Declaration was finalized before last week''s Pentagon-Anthropic standoff, but the collision of the two events wasn’t lost on anyone involved.', 'The Pro-Human Declaration was finalized before last week''s Pentagon-Anthropic standoff, but the collision of the two events wasn’t lost on anyone involved.')
on conflict (url) do update set
  feed_id = excluded.feed_id,
  feed_name = excluded.feed_name,
  title = excluded.title,
  topic = excluded.topic,
  published_at = excluded.published_at,
  fetched_at = excluded.fetched_at,
  full_text = excluded.full_text,
  summary = excluded.summary;
commit;
